spring.application.name=springboot_example
server.port=9090
g58.message=Hello Spring Boot
mailing.message=g58.message 
mailing.password=securepassword
mailing.port=9090
#spring.datasource.url=
#spring.datasource.name=postgres
#spring.datasource.password=2006
#spring.datasource.driver-class-name=org.postgresql.Driver


